### ISSUE TITLE
Pgn-downloader not working anymore

### ISSUE THREAD

**Issue by chessdjw** [Simske/pgn-downloader#12]
Executing pgn-downloader with

`pgn-downloader --since 1d chess.com chessdjw`

runs into the following error:

> pgn-downloader 0.2.0
> Downloading games for user 'chessdjw' from chess.com
> Filters:
>     Color: both
>     Date: since 2023-09-18 00:00:00+02:00 until now
>     Modes: blitz, rapid, classical, correspondence
> 
> An Error occured:
> Expecting value: line 1 column 1 (char 0)

Maybe there was an incompatible change in the API?

**Comment by Simske** [comment]
chess.com started requiring a user-agent for the API which includes contact info to the developer: https://www.chess.com/announcements/view/breaking-change-user-agent-contact-info-required

PR will be opened shortly.
