### ISSUE TITLE
Can't download games from closed lichess accounts

### ISSUE THREAD

**Issue by LiteMods000** [Simske/pgn-downloader#14]
Downloading games for user 'haydon' from lichess
Filters:
    Color: both
    Date: since Account creation until now
    Modes: blitz, rapid, classical, correspondence

An Error occured:
404 Client Error: Not Found for url: https://lichess.org/api/games/user/haydon?sort=dateAsc&perfType=blitz%2Crapid%2Cclassical%2Ccorrespondence

Link to lichess profile: https://lichess.org/@/haydon

**Comment by Simske** [comment]
The Lichess API doesn't provide a way to download games for a closed account, so there is no solution in the scope of this tool.
I'm guessing the only way to access the games would be to download all games from the Lichess archive (https://database.lichess.org/), and filter out the games of the user. This of course means downloading and filtering a lot of data.
