### ISSUE TITLE
Crashes on iPhone March 2021

### ISSUE THREAD

**Issue by DiagothecatVanCity** [Simske/pgn-downloader#4]
Hi There

I have iPhone XS Max running 14.4
App crashes on start 90% of the time.
I think it happens when I finish a game and leave the app at that point.

**Comment by Simske** [comment]
Hi, I think you got the wrong project, this is just a Python package to download games from chess.com, and has nothing to do with any iPhone app. So this is the wrong place to report.

I hope your crash problems get solved on the right project!

**Comment by DiagothecatVanCity** [comment]
ok thx for info
